stages:
    - deploy
    - publish

    
before_script:
  - export NOW=$(date +"%Y%m%d-%H%M%S")
  - export NOWS=$(date +"%Y%m%d")
  - export TAR_NAME_POSTFIX=$NOW
  - export SYS=`uname -s`
  - if [ "$SYS" == "Linux" ];then export NPROC=`nproc`;else export NPROC=4;fi
  - echo "[$CI_RUNNER_DESCRIPTION] $SYS $CI_JOB_NAME Working directory:$PWD tag $CI_COMMIT_REF_NAME CPUS:$NPROC"
  - export ARCH=`uname -m`
  - eval export `cat /etc/*-release|grep -e "^VERSION_ID="|tr -d "\" "`
  - eval export `cat /etc/*-release|grep -e "^ID="|tr -d "\" "`
  - export REV_POSTFIX=$CI_COMMIT_REF_NAME-$ID-$VERSION_ID-$ARCH
  - export DISTRIB_NAME=chaos_dashboard-$TAR_NAME_POSTFIX
  - export DISTRIB_PREFIX=/usr/local/chaos/chaos-distrib
  - export INSTALL_DIR=$DISTRIB_PREFIX
  - export CHAOS_MDS=localhost:5000
  - export CHAOS_INTERFACE=lo
  - export CHAOS_LIVE_SERVERS=couchbase
  - export CHAOS_DB_SERVERS=mongo
  - export PATH=/usr/local/chaos/qt-56/bin:$PATH
  - echo "Running on $ID $VERSION_ID $ARCH (distrib name '$DISTRIB_NAME')"
  - git config --global user.email andrea.michelotti@lnf.infn.it
  - git config --global user.name amichelo
  - git config --global color.ui true

deploy-chaos-web:
    tags:
      - lnf
    stage: deploy
    image: baltig.infn.it:4567/chaos-lnf-control/chaos_bundle_compilation:lite
    script:
      - ver=`git log --pretty=format:'%h' -n 1`
      - buildstr="$CI_COMMIT_REF_NAME-$NOWS-$ver-$CI_JOB_ID"
      - echo "<script>const VERSION=\"$buildstr\";</script>" > version.html
      - if [ "$CI_COMMIT_REF_NAME" == "master" ];then echo "   <b><font size=\"4\" color=\"red\">Production</font></b><font size=\"1\"> build: $buildstr</font>" >> version.html; else echo "   <b><font size=\"4\" color=\"green\">$CI_COMMIT_REF_NAME</font></b><font size=\"1\">  build: $buildstr</font>" >> version.html;fi
      - tar cfz $DISTRIB_NAME.tar.gz *
      - scp $DISTRIB_NAME.tar.gz  chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/noarch/
      - ssh chaosweb@opensource.lnf.infn.it "ln -sf /var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/noarch/$DISTRIB_NAME.tar.gz  /var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/noarch/latest.tar.gz"

    artifacts:
      name: "chaos_dashboard.tar.gz"
      paths:
      - ./*.tar.gz
      expire_in: 3 day
      when: always
        
  
pages:
  stage: publish
  dependencies:
    - deploy-chaos-web
  image: baltig.infn.it:4567/chaos-lnf-control/chaos_bundle_compilation:lite
  script:
    - mkdir chaos_dashboard;tar xvfz $DISTRIB_NAME.tar.gz -C chaos_dashboard
    
  allow_failure: true
  artifacts:
    paths:
    - 'chaos_dashboard'
    expire_in: 3 day
  