stages:
    - deploy
    
before_script:
  - export NOW=$(date +"%Y%m%d-%H%M%S")
  - export TAR_NAME_POSTFIX=$NOW
  - export SYS=`uname -s`
  - if [ "$SYS" == "Linux" ];then export NPROC=`nproc`;else export NPROC=4;fi
  - echo "[$CI_RUNNER_DESCRIPTION] $SYS $CI_JOB_NAME Working directory:$PWD tag $CI_COMMIT_REF_NAME CPUS:$NPROC"
  - export ARCH=`uname -m`
  - eval export `cat /etc/*-release|grep -e "^VERSION_ID="|tr -d "\" "`
  - eval export `cat /etc/*-release|grep -e "^ID="|tr -d "\" "`
  - export REV_POSTFIX=$CI_COMMIT_REF_NAME-$ID-$VERSION_ID-$ARCH
  - export DISTRIB_NAME=chaos-distrib-$REV_POSTFIX
  - export DISTRIB_PREFIX=/usr/local/chaos/chaos-distrib
  - export INSTALL_DIR=$DISTRIB_PREFIX
  - export CHAOS_MDS=localhost:5000
  - export CHAOS_INTERFACE=lo
  - export CHAOS_LIVE_SERVERS=couchbase
  - export CHAOS_DB_SERVERS=mongo
  - export PATH=/usr/local/chaos/qt-56/bin:$PATH
  - echo "Running on $ID $VERSION_ID $ARCH (distrib name '$DISTRIB_NAME')"
  - git config --global user.email andrea.michelotti@lnf.infn.it
  - git config --global user.name amichelo
  - git config --global color.ui true

deploy-ubuntu1404:
    tags:
      - chaos
    stage: deploy
    image: baltig.infn.it:4567/chaos-lnf-control/chaos_bundle_compilation:lite
    script:
      - echo $K8S_SECRET_SSKEY > ~/.ssh/id_rsa;echo $K8S_SECRET_SSKEY_PUB > ~/.ssh/id_rsa.pub;chmod 600 ~/.ssh/id_rsa;cat ~/.ssh/id_rsa;cat ~/.ssh/id_rsa.pub
      
      - ver=`git log --pretty=format:'%h' -n 1`
      - echo "<font size="4">  ($ver)</font>" > version.html
      - if [ -n "$DEPLOY" ]; then if [ $CI_COMMIT_REF_NAME == "development" ] || [ "$DEPLOY" == "ALL" ];then echo "   <b><font size="4" color=\"green\">Development/Preproduction</font></b>" > target.html;scp -rv * chaos@chaost-webui1.chaos.lnf.infn.it:/var/www/html/chaos/chaos_dashboard;scp -rv * chaos@chaost-webui2.chaos.lnf.infn.it:/var/www/html/chaos/chaos_dashboard;fi;if [ $CI_COMMIT_REF_NAME == "master" ] || [ "$DEPLOY" == "ALL" ];then echo "   <b><font size="4" color=\"red\">Production</font></b>" > target.html;scp -rv * chaos@chaos-webui01.chaos.lnf.infn.it:/usr/local/chaos/chaos-distrib/html//chaos_dashboard;scp -rv * chaos@chaos-webui02.chaos.lnf.infn.it:/usr/local/chaos/chaos-distrib/html/chaos_dashboard;scp -rv * chaos@chaos-webui03.chaos.lnf.infn.it:/usr/local/chaos/chaos-distrib/html/chaos_dashboard;scp -rv * chaos@chaos-webui1.chaos.lnf.infn.it:/var/www/html/chaos/chaos_dashboard;scp -rv * chaos@chaos-webui2.chaos.lnf.infn.it:/var/www/html/chaos/chaos_dashboard;fi;fi
      
  
